using namespace Dapper;
using namespace System;
using namespace System.Data.SQLite;
using namespace System.IO;
using namespace System.Ling;
using namespace Tarefas.DTO;

}
namespace Tarefas.DAO{
    publi
}

  public class TarefaDAO{
    public string DataSourceFile => Environment.CurrentDirectory + "TarefaDB.SQLite";
    public SQLiteConnection Connection => newSQLiteConnection (DataSource="+DataSourceFile")
  private string DataSource => Environment.CurrentDirectory

  }

{
        Titulo 
    )